const products = [
  {
    id: 1,
    name: "Eggs",
  },
  {
    id: 2,
    name: "Milk",
    types: [
      "Chocolate milk",
      "Raw milk",
      "Condensed milk",
      "A2 milk",
      "Evaporated milk",
      "Goat milk",
      "Lactose free milk",
      "Kefir",
      "Infant formula",
      "Vat pasteurized milk",
      "Buttermilk",
      "Biodynamic Milk",
    ],
  },
  {
    id: 3,
    name: "Butter",
    types: ["Ghee"],
  },
  {
    id: 4,
    name: "Cheese",
    types: ["Paneer", "Cream cheese", "Goat cheese", "Raw cheese"],
  },
  {
    id: 5,
    name: "Cream",
    types: ["Sour cream", "Whipped Cream"],
  },
  {
    id: 6,
    name: "Ice Cream",
  },
  {
    id: 7,
    name: "Chocolate",
  },
  {
    id: 8,
    name: "Beef",
    types: [
      "Elk",
      "Buffalo",
      "Venison",
      "Bison",
      "Retail Cuts",
      "Bulk",
      "Ground",
      "Sausages",
      "Hot Dogs",
      "Veal",
      "Live",
      "Jerky",
      "Organs",
      "Beef bacon",
      "Wholesale",
      "Half",
      "Quarter",
      "Eigths",
      "Custom",
      "Bones",
    ],
  },
  {
    id: 9,
    name: "Pet Food",
    types: ["Poultry", "Beef"],
  },
  {
    id: 10,
    name: "Poultry",
    types: [
      "Chicken",
      "Turkey",
      "Duck",
      "Ostrich",
      "Kosher",
      "Soy free",
      "Sausage",
      "Canned chicken",
      "Processed meat",
    ],
  },
  {
    id: 11,
    name: "Yogurt",
    types: ["Frozen Yogurt", "Greek Yogurt", "Soy Yogurt", "Skyr"],
  },
  {
    id: 12,
    name: "Plant Based Beverages",
    types: [
      "Soy",
      "Almond",
      "Oat",
      "Pistachio/Almond",
      "Cashew",
      "Banana",
      "Coconut",
      "Rice",
      "Hazelnut",
      "Blend",
      "Hemp",
      "Quinoa",
      "Flax",
      "Macadamia",
      "Pea",
    ],
    organic: ["No"],
  },
  {
    id: 13,
    name: "Snack Bar",
    organic: ["No", "Made with organic ingredients"],
  },
  {
    id: 14,
    name: "Cottage Cheese",
    organic: ["No"],
  },
  {
    id: 15,
    name: "Cereal",
  },
  {
    id: 16,
    name: "Tofu",
    types: [
      "Tofu Ravioli",
      "Tofu Veggie Patties",
      "Tofu Hot Dogs",
      "Tofurky",
      "Tofu Spreads",
      "Tofu Salad (No Egg)",
    ],
  },
  {
    id: 17,
    name: "Other Soy Products",
  },
];

export default products;
